-- 제 3 정규화

-- 정규화 -- 데이터를 어떻게 쌓을 것인가에 대한 문제 
-- 제 1정규화 -- 

-- 코드성 값
CREATE TABLE CIDO
(
	CODEID		CHAR(4)		NOT NULL PRIMARY KEY,
	CODENAME	VARCHAR2(200)	 NOT NULL,
	CODEEXIT	VARCHAR2(1000)	 NULL
);
INSERT INTO CIDO VALUES('C001', '서울', NULL);
INSERT INTO CIDO VALUES('C002', '인천', NULL);
INSERT INTO CIDO VALUES('C003', '경기', NULL);
INSERT INTO CIDO VALUES('C004', '강원', NULL);
INSERT INTO CIDO VALUES('C005', '충북', NULL);
INSERT INTO CIDO VALUES('C006', '충남', NULL);
INSERT INTO CIDO VALUES('C007', '대전', NULL);
INSERT INTO CIDO VALUES('C008', '세종', NULL);
INSERT INTO CIDO VALUES('C009', '전북', NULL);
INSERT INTO CIDO VALUES('C010', '전남', NULL);
INSERT INTO CIDO VALUES('C011', '광주', NULL);
INSERT INTO CIDO VALUES('C012', '경북', NULL);
INSERT INTO CIDO VALUES('C013', '대구', NULL);
INSERT INTO CIDO VALUES('C014', '경남', NULL);
INSERT INTO CIDO VALUES('C015', '울산', NULL);
INSERT INTO CIDO VALUES('C016', '창원', NULL);
INSERT INTO CIDO VALUES('C017', '부산', NULL);
INSERT INTO CIDO VALUES('C018', '김해', NULL);

--COMMIT;
