-- 계층형 연습 문제 

-- 학과 LPAD
SELECT 
	LPAD(' ', COM_LVL * 3) || COM_VAL || '(' || COM_ID || ')'
FROM 
	COMMONS_TBL
WHERE 
	GRP_ID = 'GRP002'
START WITH 
	PARENT_ID = 'COM1000'
CONNECT BY PRIOR 
	COM_ID = PARENT_ID
;

-- 학과 LPAD
SELECT 
	LPAD(' ', COM_LVL * 3) || COM_VAL || '(' || COM_ID || ')'
FROM 
	COMMONS_TBL
WHERE 
	GRP_ID = 'GRP001'
START WITH 
	PARENT_ID = 'COM0000'
CONNECT BY PRIOR
	COM_ID = PARENT_ID
;