SELECT CODEID, LPAD(' ', CODELVL *1) || CODENAME, PARENTID, CODELVL 
FROM CODES
WHERE GROUPID='CIDO'					--메뉴 목록 제외 
START WITH PARENTID IS NULL
CONNECT BY PRIOR CODEID = PARENTID
;

SELECT * FROM CODES T1, CODES T2
WHERE T1.CODEID = T2.PARENTID
AND T1.GROUPID = 'CIDO'
;

SELECT T2.CODEID, T2.CODENAME, T3.CODENAME, COUNT(*)
FROM STUDENTS T1, CODES T2, CODES T3
WHERE T1.SADDR = T2.CODEID
AND T2.PARENTID = T3.CODEID
AND T2.GROUPID = 'CIDO'
GROUP BY T2.CODEID, T2.CODENAME, T3.CODENAME
;
-- COMMIT;


--각 동별로 살고있는 숫자를 --동이름, 숫자