-- Q. 학생 별 출석률 구하기
SELECT COUNT(*) FROM
(
SELECT TO_CHAR(ADATE, 'YYYY-MM-DD') AS ATT
FROM ATTENDANCE
GROUP BY TO_CHAR(ADATE, 'YYYY-MM-DD')
)
;			-- 모든 학생이 결석할 경우 카운트하지 않는다는 문제점이 있음.


-- 학생이 하루에 두 번 이상 출첵을 했는 지 확인
-- 학생 별, 날짜 별 출석 횟수
SELECT SID, TO_CHAR(ADATE, 'YYYY-MM-DD AM HH:MI:SS'), COUNT(*)
FROM ATTENDANCE
GROUP BY SID, TO_CHAR(ADATE, 'YYYY-MM-DD AM HH:MI:SS');
 
 
 --1. 학생 별 출석률 구하기
 
 --학생 별 출석 횟수  (과목 상관 X)
 SELECT T2.SID, T1.SNAME, COUNT(*) AS CNT,
	 (SELECT COUNT(*) FROM SUBJECTS) * 
		 (
		 SELECT COUNT(*) FROM
			(
			 SELECT TO_CHAR(ADATE, 'YYYY-MM-DD') AS ATT
			 FROM ATTENDANCE
			 GROUP BY TO_CHAR(ADATE, 'YYYY-MM-DD')
			)
	 ) AS TLTCNT
 FROM STUDENTS T1, ATTENDANCE T2
 WHERE T1.SID = T2.SID
 GROUP BY T2.SID, T1.SNAME;
 
 --위 코드 정리 
 SELECT A.SID, A.SNAME, A.CNT, B.SUBCNT, C.TLTCNT, 
		ROUND(A.CNT/(B.SUBCNT*C.TLTCNT)*100, 2) || '%' AS PERSENT 
 FROM
 (
	 SELECT T1.SID, T1.SNAME, COUNT(*) AS CNT
	 FROM STUDENTS T1, ATTENDANCE T2
	 WHERE T1.SID= T2.SID
	 GROUP BY T1.SID, T1.SNAME
 )A
 ,
 (
	SELECT COUNT(*) AS SUBCNT FROM SUBJECTS
 )B
 ,
 (
	 SELECT COUNT(*) AS TLTCNT FROM				
	 (
		 SELECT TO_CHAR(ADATE, 'YYYY-MM-DD') AS ATT
		 FROM ATTENDANCE
		 GROUP BY TO_CHAR(ADATE, 'YYYY-MM-DD')
	 )
 )C;
 
 
 
 --학생 한 명이 모든 과목을 모두 출석할 경우의 출석 횟수
 SELECT COUNT(*) FROM SUBJECTS;		--과목의 경우의 수 
 
 SELECT COUNT(*) FROM				--날짜의 경우의 수
 (
 SELECT TO_CHAR(ADATE, 'YYYY-MM-DD') AS ATT
 FROM ATTENDANCE
 GROUP BY TO_CHAR(ADATE, 'YYYY-MM-DD')
 )
 ;	
 
 -- 2021년 학생들의 출석률을 주차별
 
 -- 날짜별 학생별 출석현황 --날짜, 학생아이디, 이름, 출석 횟수
 SELECT T1.SID, T1.SNAME, TO_CHAR(ADATE, 'YYYYMMDD'), COUNT(*) AS CNT
 FROM STUDENTS T1, ATTENDANCE T2
 WHERE T1.SID = T2.SID
 GROUP BY T1.SID, T1.SNAME, TO_CHAR(ADATE, 'YYYYMMDD')
 ORDER BY T1.SID, T1.SNAME
 ;
 
 --20210405 결석을 한과목이라도 한 학생들 리스트 -- 학생아이디, 이름  >> 집가서 해보기 
 SELECT * FROM ATTENDANCE
 WHERE TO_CHAR(ADATE,'YYYYMMDD') = '20210405'
 ;
 
 SELECT * FROM STUDENTS T1, ATTENDANCE T2
 WHERE T1.SID = T2.SID(+)
 AND TO_CHAR(ADATE,'YYYYMMDD') = '20210405'
 ;
 
 
 