/*
	도시 시 
*/

CREATE TABLE CODES(
	CODEID		CHAR(4)				PRIMARY KEY,
	CODENAME	VARCHAR2(200)		NOT NULL,
	PARENTID	CHAR(4)				NULL,
	CODELVL		INT					NOT NULL		
);

INSERT INTO CODES VALUES ('C001', '시도코드', NULL, 0);

--시도
INSERT INTO CODES VALUES ('C002', '부산', 'C001', 1);

--부산시 -구
INSERT INTO CODES VALUES ('C005', '금정구', 'C002', 2);
INSERT INTO CODES VALUES ('C006', '동래구', 'C002', 2);
INSERT INTO CODES VALUES ('C007', '해운대구', 'C002', 2);

--부산시 금정구 -동
INSERT INTO CODES VALUES ('C008', '구서동', 'C005', 3);
INSERT INTO CODES VALUES ('C009', '남산동', 'C005', 3);

--부산시 동래구 -동
INSERT INTO CODES VALUES ('C010', '칠산동', 'C006', 3);
INSERT INTO CODES VALUES ('C011', '연산동', 'C006', 3);
INSERT INTO CODES VALUES ('C012', '사직동', 'C006', 3);

--부산시 해운대구 -동
INSERT INTO CODES VALUES ('C013', '우동', 'C007', 3);
INSERT INTO CODES VALUES ('C014', '좌동', 'C007', 3);


--경남
INSERT INTO CODES VALUES ('C003', '경남', 'C001', 1);

--경남 시 0 김해 김해
INSERT INTO CODES VALUES ('C015', '김해', 'C003', 2);
INSERT INTO CODES VALUES ('C016', '창원', 'C003', 2);

INSERT INTO CODES VALUES ('C017', '외동', 'C016', 3);
INSERT INTO CODES VALUES ('C018', '내동', 'C016', 3);

--경남 창원 구
INSERT INTO CODES VALUES ('C019', '창원구', 'C016', 3);
INSERT INTO CODES VALUES ('C020', '마산구', 'C016', 3);


--경남 창원 창원구 동
INSERT INTO CODES VALUES ('C021', '사파정동', 'C019', 4);
INSERT INTO CODES VALUES ('C022', '성산동', 'C019', 4);
INSERT INTO CODES VALUES ('C023', '의창동', 'C019', 4);

--경남 창원 마산구 동
INSERT INTO CODES VALUES ('C024', '합포동', 'C020', 4);
INSERT INTO CODES VALUES ('C025', '양덕동', 'C020', 4);
INSERT INTO CODES VALUES ('C026', '의성동', 'C020', 4);

--울산
INSERT INTO CODES VALUES ('C004', '울산', 'C001', 1);

--울산 구
INSERT INTO CODES VALUES ('C027', '동구', 'C004', 2);
INSERT INTO CODES VALUES ('C028', '남구', 'C004', 2);

--울산 동구 동
INSERT INTO CODES VALUES ('C029', '방어동', 'C027', 3);
INSERT INTO CODES VALUES ('C030', '전하동', 'C027', 3);

--울산 남구 동
INSERT INTO CODES VALUES ('C033', '신성1동', 'C028', 3);
INSERT INTO CODES VALUES ('C034', '신성2동', 'C028', 3);

--COMMIT;

SELECT CODEID
	,LPAD(' ', CODELVL * 1 )|| CODENAME, CODELVL
FROM CODES
START WITH CODEID = 'C038'			--어디서 시작할지
CONNECT BY PRIOR CODEID = PARENTID
;


--시도만 가져오기 
SELECT * FROM CODES
WHERE PARENTID = 'C001';


SELECT * FROM STUDENTS T1, CODES T2, CODES T3, CODES T4, CODES T5
WHERE T1.SADDR = T2.CODEID
AND T2.PARENTID = T3.CODEID
AND T3.PARENTID = T4.CODEID
AND T4.PARENTID = T5.CODEID
;


-- 모든 지역 리스트 



------ 조직도 

INSERT INTO CODES VALUES ('C036', '메뉴트리구조도', NULL, 0);

INSERT INTO CODES VALUES ('C037', '전자제품', 'C033', 1);
INSERT INTO CODES VALUES ('C035', '화장품', 'C033', 1);

INSERT INTO CODES VALUES ('C038', '조직도', NULL, 0);

INSERT INTO CODES VALUES ('C039', '조직도', 'C038', 1);
INSERT INTO CODES VALUES ('C040', '조직도', 'C038', 1);
INSERT INTO CODES VALUES ('C041', '조직도', 'C038', 1);




