
SELECT *
FROM
(
	SELECT T1.CODENAME AS CODENAME1, 
		   T2.CODENAME AS CODENAME2, 
		   T3.CODEID AS CODEID3, 
		   T3.CODENAME AS CODENAME3, 
		   T4.CODEID AS CODEID4, 
		   T4.CODENAME AS CODENAME4
	FROM CODES T1, CODES T2, CODES T3, CODES T4
	WHERE T1.CODEID = T2.PARENTID(+)
	AND T2.CODEID = T3.PARENTID(+)
	AND T3.CODEID = T4.PARENTID(+)
	AND T1.PARENTID IS NOT NULL
	AND T2.PARENTID IS NOT NULL
	AND T3.PARENTID IS NOT NULL
	AND T3.CODELVL != 4
)A, STUDENTS B
WHERE DECODE(A.CODEID4, NULL, CODEID3, CODEID4 ) = B.SADDR
;
