-- 학생 아이디, 학생 이름, 총점, 평균, 순위 

-- 1. 학생들이 어떤 과목을 수강신청했느지를 찾는다.
	SELECT T1.STU_ID, T1.STU_NAME, T3.SUB_ID, T3.SUB_NAME, T3.DO_YEAR, T3.SEMESTER
			, T4.GRP_ID, T4.COM_ID, T4.COM_VAL
	FROM STUDENTS_TBL T1, STUDENTS_TIME_TBL T2, SUBJECTS_TBL T3, COMMONS_TBL T4 --T3의 KEY는 3개의 컬럼을 묶어서
	WHERE T1.STU_ID = T2.STU_ID 
	AND T2.SUB_ID = T3.SUB_ID
	AND T2.DO_YEAR = T3.DO_YEAR
	AND T2.SEMESTER = T3.SEMESTER
	
	AND T1.STU_DEPT_GRP = T4.GRP_ID AND T1.STU_DEPT = T4.COM_ID
	ORDER BY T1.STU_ID
	;
	
	-- 학생들의 수강신청 내역 X 중간 기말 크로스조인 
	-- 2018년도 1학기 전체 시험 성적 
	-- 학생아이디, 학생이름, 과목아이디, 년도, 학기, 구분, 시험점수, 해당학과 
	SELECT
		A.STU_ID, A.STU_NAME, A.SUB_ID, A.SUB_NAME, A.DO_YEAR, A.SEMESTER, B.GUBUN, NVL(C.SCORE,0) AS SCORE
		,A.GRP_ID, A.COM_ID, A.COM_VAL
	FROM
	(
		SELECT T1.STU_ID, T1.STU_NAME, T3.SUB_ID, T3.SUB_NAME, T3.DO_YEAR, T3.SEMESTER
				, T4.GRP_ID, T4.COM_ID, T4.COM_VAL
		FROM STUDENTS_TBL T1, STUDENTS_TIME_TBL T2, SUBJECTS_TBL T3, COMMONS_TBL T4 --T3의 KEY는 3개의 컬럼을 묶어서
		WHERE T1.STU_ID = T2.STU_ID 
		AND T2.SUB_ID = T3.SUB_ID
		AND T2.DO_YEAR = T3.DO_YEAR
		AND T2.SEMESTER = T3.SEMESTER
	
		AND T1.STU_DEPT_GRP = T4.GRP_ID AND T1.STU_DEPT = T4.COM_ID
	)A, 
	( 
		SELECT GUBUN FROM 
		SCORES_TBL 
		GROUP BY GUBUN
	)B, SCORES_TBL C
	WHERE A.STU_ID = C.STU_ID(+)
	AND A.SUB_ID = C.SUB_ID(+)
	AND A.DO_YEAR = C.DO_YEAR(+)
	AND A.SEMESTER = C.SEMESTER(+)
	AND B.GUBUN = C.GUBUN(+)
	AND B.GUBUN LIKE '%'|| : IN_GUBUN ||'%'
	
	ORDER BY A.STU_ID,A.SUB_ID,B.GUBUN
	;
	
	
-- 학생 아이디, 학생 이름, 총점, 평균, 순위 
	SELECT
		A.STU_ID, A.STU_NAME
		, MAX(A.COM_ID) AS COM_ID, MAX(A.COM_VAL) AS COM_VAL
		,SUM(NVL(C.SCORE, 0))
		,ROUND(AVG(NVL(C.SCORE, 0)),2)
		,DENSE_RANK() OVER(ORDER BY ROUND(AVG(NVL(C.SCORE, 0)),2) DESC) AS RNK
	FROM
	(		--적어도 수강신청한 학생들 (안하면 휴학~)
			SELECT T1.STU_ID, T1.STU_NAME, T3.SUB_ID, T3.SUB_NAME, T3.DO_YEAR, T3.SEMESTER
					, T4.GRP_ID, T4.COM_ID, T4.COM_VAL
			FROM STUDENTS_TBL T1, STUDENTS_TIME_TBL T2, SUBJECTS_TBL T3, COMMONS_TBL T4 --T3의 KEY는 3개의 컬럼을 묶어서
			WHERE T1.STU_ID = T2.STU_ID 
			AND T2.SUB_ID = T3.SUB_ID
			AND T2.DO_YEAR = T3.DO_YEAR
			AND T2.SEMESTER = T3.SEMESTER
			
			AND T1.STU_DEPT_GRP = T4.GRP_ID AND T1.STU_DEPT = T4.COM_ID
	)A, 
	( 
		SELECT GUBUN FROM 
		SCORES_TBL 
		GROUP BY GUBUN
	)B, SCORES_TBL C
	WHERE A.STU_ID = C.STU_ID(+)
	
	AND A.SUB_ID = C.SUB_ID(+)
	AND A.DO_YEAR = C.DO_YEAR(+)
	AND A.SEMESTER = C.SEMESTER(+)
	
	AND B.GUBUN = C.GUBUN(+)
	AND C.GUBUN = 2
GROUP BY A.STU_ID, A.STU_NAME
;




------------------------------------------------------------------------ 연습
SELECT * FROM SCORES_TBL;
SELECT * FROM STUDENTS_TBL;
SELECT * FROM STUDENTS_TIME_TBL;
SELECT * FROM SUBJECTS_TBL;

-- 모든 학생들의 시험 리스트
SELECT
	A.STU_ID, A.STU_NAME, A.SUB_ID, A.SUB_NAME, A.DO_YEAR, A.SEMESTER
	,B.GUBUN, NVL(C.SCORE,0)
FROM
(
	SELECT T2.STU_ID, T2.STU_NAME, T3.SUB_ID, T3.SUB_NAME, T3.DO_YEAR, T3.SEMESTER
	FROM STUDENTS_TIME_TBL T1, STUDENTS_TBL T2, SUBJECTS_TBL T3
	WHERE T1.STU_ID = T2.STU_ID
	
	AND T1.SUB_ID = T3.SUB_ID 
	AND T1.DO_YEAR = T3.DO_YEAR 
	AND T1.SEMESTER = T3.SEMESTER
)A,
(	SELECT GUBUN 
	FROM SCORES_TBL 
	GROUP BY GUBUN 
)B, SCORES_TBL C
WHERE
		A.STU_ID = C.STU_ID(+)
	AND B.GUBUN = C.GUBUN(+)
	
	AND A.SUB_ID = C.SUB_ID(+) 
	AND A.DO_YEAR = C.DO_YEAR(+) 
	AND A.SEMESTER = C.SEMESTER(+)
ORDER BY A.STU_ID, A.SUB_ID
;
----------------------------------------------------------------------------------
-- 중간 기말 나누기 / 총합, 평균
-- 만족 
SELECT
	A.STU_ID, A.STU_NAME, (A.DO_YEAR || '년도 ' || A.SEMESTER || '학기 ' || DECODE(B.GUBUN,1,'중간고사','기말고사')) AS 시험
	,SUM(C.SCORE) AS STUSUM
	,ROUND(SUM(C.SCORE)/COUNT(A.SUB_ID),2) AS STUAVG
	,DENSE_RANK() OVER(ORDER BY ROUND(AVG(C.SCORE),2) DESC) AS RNK 
FROM
(
	SELECT T2.STU_ID, T2.STU_NAME, T3.SUB_ID, T3.SUB_NAME, T3.DO_YEAR, T3.SEMESTER, T4.COM_VAL
	FROM STUDENTS_TIME_TBL T1, STUDENTS_TBL T2, SUBJECTS_TBL T3, COMMONS_TBL T4
	WHERE T1.STU_ID = T2.STU_ID
	
	AND T1.SUB_ID = T3.SUB_ID 
	AND T1.DO_YEAR = T3.DO_YEAR 
	AND T1.SEMESTER = T3.SEMESTER
	
	AND T2.STU_DEPT_GRP = T4.GRP_ID
	AND T2.STU_DEPT = T4.COM_ID
)A,
(	SELECT GUBUN
	FROM SCORES_TBL 
	GROUP BY GUBUN 
)B, SCORES_TBL C
WHERE
		A.STU_ID = C.STU_ID(+)
	AND B.GUBUN = C.GUBUN(+)
	AND B.GUBUN LIKE '%' || : IN_GUBUN || '%'
	
	AND A.SUB_ID = C.SUB_ID(+) 
	AND A.DO_YEAR = C.DO_YEAR(+) 
	AND A.SEMESTER = C.SEMESTER(+)
GROUP BY A.STU_ID, A.STU_NAME, (A.DO_YEAR || '년도 ' || A.SEMESTER || '학기 ' || DECODE(B.GUBUN,1,'중간고사','기말고사'))
;






