create or replace NONEDITIONABLE PROCEDURE PROC_DEL_TEST_TBL
(
	IN_IDX		IN	NUMBER
	,O_ERRCODE	OUT	VARCHAR2
	,O_ERRMSG	OUT	VARCHAR2
)AS
	
	V_CNT_IDX		NUMBER(1);
	IDX_EXCEPTION	EXCEPTION;
	
BEGIN

	SELECT DECODE(MAX(IDX),NULL, 0, 1)
	INTO V_CNT_IDX
	FROM TEST_TBL
	WHERE IDX = IN_IDX
	;
	
	IF V_CNT_IDX = 0 THEN
		RAISE IDX_EXCEPTION;
	
	ELSE 
		DELETE FROM TEST_TBL			-- ID 중간 값이 지워졌을 때 그 뒤에 있는 아이디를 순차적으로 -1 시키는
		WHERE IDX = IN_IDX
		;
	
		UPDATE TEST_TBL
		SET IDX = IDX -1
		WHERE IDX > IN_IDX
		;
	END IF;
	
	EXCEPTION
	WHEN IDX_EXCEPTION THEN
	O_ERRCODE := 'ERR101';
	O_ERRMSG := '삭제할 데이터가 없습니다.';
	
	WHEN OTHERS THEN
	O_ERRCODE := SQLCODE;
	O_ERRMSG := SQLERRM;
	--ROLLBACK 안줘도 됌
	
END PROC_DEL_TEST_TBL;