CREATE OR REPLACE PROCEDURE PROC_INS_TEST_TBL 
(
  IN_NAME IN VARCHAR2 
) AS 
	
	V_NEW_IDX		NUMBER(10);
	V_NEXTVAL		NUMBER(10);
	
BEGIN

	SELECT NVL(MAX(IDX),0) +1
	INTO V_NEW_IDX
	FROM TEST_TBL
	;
	 
	-- 변수로 NEXTVAL로 사용하는 것이 아니라 데이터가 현재 몇 개가 들어가 있는 지 확인할 수 있다 
	SELECT SEQ_TEST_TBL.NEXTVAL 
	INTO V_NEXTVAL
	FROM DUAL;
	
	INSERT INTO TEST_TBL(IDX, NAME)
	VALUES (V_NEW_IDX, IN_NAME)
	-- VALUES (SEQ_TEST_TBL.NEXTVAL, IN_NAME);
	;
  
END PROC_INS_TEST_TBL;