CREATE OR REPLACE 
PACKAGE PKG_COMMONS AS 

  -- GRPCOMMONS_TBL INSERT
  PROCEDURE PROC_INS_GRPCOMMONS
  (
	   IN_GRP_NAME 		IN 	VARCHAR2
  );
	

	-- GRPCOMMONS_TBL SELECT
	PROCEDURE PROC_SEL_GRPCOMMONS
	(
		  IN_GRP_ID		IN	VARCHAR2
		, IN_GRP_NAME	IN	VARCHAR2
		, O_CUR		OUT	SYS_REFCURSOR
	);
	
	-- GRPCOMMONS_TBL UPDATE
	PROCEDURE PROC_UP_GRPCOMMONS
	(
		  IN_GRP_ID		IN	VARCHAR2
		, IN_GRP_NAME	IN	VARCHAR2
	);
	
	-- GRPCOMMONS_TBL DELETE
	PROCEDURE PROC_DEL_GRPCOMMONS
	(
		  IN_GRP_ID 	IN 	VARCHAR2
	);
	
	
-------------------------------------------------------------------------------
	--COMMONS_TBL INSERT
	PROCEDURE PROC_INS_COMMONS
	(
		  IN_GRP_ID		IN 	VARCHAR2
		, IN_COM_VAL	IN	VARCHAR2
		, IN_COM_LVL	IN	VARCHAR2
		, IN_PARENT_ID	IN	VARCHAR2
	);



	-- COMMONS_TBL SELECT
	PROCEDURE PROC_SEL_COMMONS
	(
		  IN_COM_ID		IN	VARCHAR2
		, IN_GRP_ID		IN 	VARCHAR2
		, IN_COM_VAL	IN	VARCHAR2
		, IN_COM_LVL	IN	VARCHAR2
		, IN_PARENT_ID	IN	VARCHAR2
		, O_CUR			OUT	SYS_REFCURSOR
	);
	
	
	-- COMMONS_TBL UPDATE
	PROCEDURE PROC_UP_COMMONS
	(
		  IN_COM_ID 	IN 	VARCHAR2
		, IN_GRP_ID		IN 	VARCHAR2
		, IN_COM_VAL	IN	VARCHAR2
		, IN_COM_LVL	IN	VARCHAR2
		, IN_PARENT_ID	IN	VARCHAR2
	);
	
	-- COMMONS_TBL DELETE
	PROCEDURE PROC_DEL_COMMONS
	(
		 IN_COM_ID		IN	VARCHAR2
		,IN_GRP_ID		IN 	VARCHAR2
	);
	
END PKG_COMMONS;