create or replace NONEDITIONABLE PACKAGE BODY PKG_STUDENTS AS
	-- 1. 삽입
	PROCEDURE PROC_INS_STUDENTS
	(
		  IN_STU_NAME		IN VARCHAR2
		, IN_STU_TEL		IN VARCHAR2
		, IN_STU_ADDR_GRP	IN VARCHAR2
		, IN_STU_ADDR		IN VARCHAR2
		, IN_STU_DEPT_GRP	IN VARCHAR2
		, IN_STU_DEPT		IN VARCHAR2
		, IN_STU_ADDR2		IN VARCHAR2
	)
	AS
		--변수 선언
		V_NEW_STU_ID		VARCHAR(6);

	BEGIN
		--새로운 아이디값을 찾아서 생성 후 V_NEW_STU_ID에 할당
		SELECT 'STU'|| TO_CHAR(TO_NUMBER(SUBSTR(MAX(STU_ID),4,3)) +1, 'FM000')
		INTO V_NEW_STU_ID
		FROM STUDENTS_TBL;

		INSERT INTO STUDENTS_TBL(STU_ID, STU_NAME, STU_TEL, STU_ADDR_GRP, STU_ADDR, STU_DEPT_GRP, STU_DEPT, STU_ADDR2)
		VALUES(
            V_NEW_STU_ID
            , IN_STU_NAME
            , IN_STU_TEL
            , IN_STU_ADDR_GRP
            , IN_STU_ADDR
            , IN_STU_DEPT_GRP
            , IN_STU_DEPT
            , IN_STU_ADDR2
    );
	END PROC_INS_STUDENTS;
	
	
	--2. 조회
	PROCEDURE PROC_SEL_STUDENTS
	(
		  IN_STU_ID			IN	 VARCHAR2
		, IN_STU_NAME		IN 	 VARCHAR2
		, O_CURSOR			OUT	 SYS_REFCURSOR
	)AS
	
	BEGIN
		OPEN O_CURSOR FOR
		SELECT * FROM STUDENTS_TBL
		WHERE STU_ID LIKE '%' || IN_STU_ID || '%'
		AND STU_NAME LIKE '%' || IN_STU_NAME || '%'
		;
		
	END PROC_SEL_STUDENTS;
	
	-- 3. 수정 
	PROCEDURE PROC_UP_STUDENTS
	(
		  IN_STU_ID			IN VARCHAR2
		, IN_STU_NAME		IN VARCHAR2
		, IN_STU_TEL		IN VARCHAR2
		, IN_STU_ADDR_GRP	IN VARCHAR2
		, IN_STU_ADDR		IN VARCHAR2
		, IN_STU_DEPT_GRP	IN VARCHAR2
		, IN_STU_DEPT		IN VARCHAR2
		, IN_STU_ADDR2		IN VARCHAR2
		, IN_STU_PASS		IN VARCHAR2
	)
	AS
	
	BEGIN
	    UPDATE STUDENTS_TBL 
		SET STU_NAME = IN_STU_NAME, STU_TEL = IN_STU_TEL, STU_ADDR_GRP = IN_STU_ADDR_GRP,
		STU_ADDR = IN_STU_ADDR, STU_ADDR2=IN_STU_ADDR2, STU_DEPT_GRP = IN_STU_DEPT_GRP, 
		STU_DEPT = IN_STU_DEPT,STU_PASS = IN_STU_PASS
    WHERE STU_ID = IN_STU_ID;

	END PROC_UP_STUDENTS;

	
	-- 4. 삭제 
	PROCEDURE PROC_DEL_STUDENTS
	(
		  IN_STU_ID			IN VARCHAR2
	)
	AS
	
	BEGIN
	
		DELETE FROM STUDENTS_TBL 
		WHERE STU_ID = IN_STU_ID;
	
	END PROC_DEL_STUDENTS;
END PKG_STUDENTS;
