CREATE OR REPLACE 
PACKAGE PKG_SCORES AS 
	-- SCORES_TBL INSERT
  PROCEDURE PROC_INS_SCORES
  (
		  IN_STU_ID		IN	VARCHAR2
		, IN_SUB_ID		IN	VARCHAR2
		, IN_YEAR		IN	VARCHAR2
		, IN_SEMESTER	IN	VARCHAR2
		, IN_GBN		IN	VARCHAR2
		, IN_SCORE		IN	VARCHAR2
		, IN_DATE		IN	VARCHAR2		--DATE로 넣어도 자바에서 CHAR로 변함
  );
  
  
---------------------- 선택된 학과에 대한 과목 SEL --> 원래라면 PKG_SUBJECTS에 만들어야함 

  	PROCEDURE PROC_SEL_SUBJECTS
	(
		 IN_GRP_ID		IN	VARCHAR2
		,IN_COM_ID		IN	VARCHAR2
		,O_CUR			OUT	SYS_REFCURSOR
	);
	
	
	
---------------------- 성적 등록 페이지 리스트 ( 최종결과X )
	PROCEDURE PROC_SEL_INS_SCORE
	(
		 IN_DO_YEAR		IN	VARCHAR2 
		,IN_SEMESTER	IN	VARCHAR2	
		,IN_GUBUN		IN	VARCHAR2
		,IN_GRP_ID		IN	VARCHAR2
		,IN_COM_ID		IN	VARCHAR2
		,IN_SUB_ID		IN	VARCHAR2
		,O_CUR			OUT	SYS_REFCURSOR
	);
	
END PKG_SCORES;


