create or replace PACKAGE PKG_BANK AS 

  PROCEDURE PROC_SEL_BANKLIST
  (
	IN_MID			IN	VARCHAR2
	,O_CUR			OUT	SYS_REFCURSOR
  );


	-- 이체 
	PROCEDURE PROC_INS_TRANS
	(
		 IN_SEND_BID	IN	VARCHAR2		-- 송금통장
		,IN_REC_BID		IN	VARCHAR2		-- 입금통장
		,IN_PRICE		IN	VARCHAR2
		,O_ERRCODE		OUT	VARCHAR2
		,O_ERRMSG		OUT	VARCHAR2
	);
	
	-- 회원 계좌 추가 
	PROCEDURE PROC_INS_BANKBOOK
	(
		 IN_MID			IN	VARCHAR2
		,IN_BID			IN	VARCHAR2
		,IN_BNAME		IN	VARCHAR2
		
		,O_ERRCODE		OUT	VARCHAR2
		,O_ERRMSG		OUT	VARCHAR2
		
	);
	
	PROCEDURE PROC_INS_MEMBER
	(
		IN_MNAME		IN	VARCHAR2
		,IN_MTEL		IN	VARCHAR2
		
		,O_ERRCODE		OUT	VARCHAR2
		,O_ERRMSG		OUT	VARCHAR2
	);
	
END PKG_BANK;