-- 	DECLARE 단순 곱하기 연습 

DECLARE
	V_NUM1		NUMBER(10);	
	V_NUM2		NUMBER(10);
	V_NUM3		NUMBER(10);
	
BEGIN
	V_NUM1 := 15;
	V_NUM2 := 3456;
	V_NUM3 := V_NUM1 * V_NUM2;
	
	--DBMS_OUTPUT.PUT_LINE(V_NUM3);
END;