-- DECLARE 를 사용해서 패키지 실행하기 

-- INSERT 
-- STU_ID는 프로시저에서 아이디값을 찾아서 자체적으로 할당
DECLARE
  IN_STU_NAME VARCHAR2(200);
  IN_STU_TEL VARCHAR2(200);
  IN_STU_ADDR_GRP VARCHAR2(200);
  IN_STU_ADDR VARCHAR2(200);
  IN_STU_DEPT_GRP VARCHAR2(200);
  IN_STU_DEPT VARCHAR2(200);
  IN_STU_ADDR2 VARCHAR2(200);
  
BEGIN

  IN_STU_NAME := '박길자';
  IN_STU_TEL := '010-2222-3333';
  IN_STU_ADDR_GRP := 'GRP001';
  IN_STU_ADDR := 'COM0044';
  IN_STU_DEPT_GRP := 'GRP002';
  IN_STU_DEPT := 'COM0020';
  IN_STU_ADDR2 := 'COM0015';

  PKG_STUDENTS.PROC_INS_STUDENTS( -- [패키지명],[프로시저명]()
    IN_STU_NAME => IN_STU_NAME,
    IN_STU_TEL => IN_STU_TEL,
    IN_STU_ADDR_GRP => IN_STU_ADDR_GRP,
    IN_STU_ADDR => IN_STU_ADDR,
    IN_STU_DEPT_GRP => IN_STU_DEPT_GRP,
    IN_STU_DEPT => IN_STU_DEPT,
    IN_STU_ADDR2 => IN_STU_ADDR2
  );
--rollback; 
END;
