-- 날짜별 취소한 건 완료된 건
SELECT
		TO_CHAR(F_DATE,'YYYY-MM-DD')
		,COUNT(*) AS 모든건
		,SUM(DECODE(F_GUBUN, 1, 1, 0)) AS 완료 -- 완료 건수 
		,SUM(DECODE(F_GUBUN, 2, 1, 0)) AS 취소 
FROM FINISH_DRIVE_TBL
GROUP BY TO_CHAR(F_DATE,'YYYY-MM-DD')
ORDER BY TO_CHAR(F_DATE,'YYYY-MM-DD')
;