create or replace PACKAGE PKG_DRIVER2 AS 

  -- 드라이버 CRUD
  PROCEDURE PROC_INS_DRIVER(
		IN_DR_NAME		IN		VARCHAR2
		,IN_DR_TEL		IN		VARCHAR2
		,IN_DR_GENDER	IN		VARCHAR2
		,O_ERRCODE		OUT		VARCHAR2
		,O_ERRMSG		OUT		VARCHAR2
  );
  
  PROCEDURE PROC_SEL_DRIVER(
		O_CURSOR		OUT 	SYS_REFCURSOR
		,O_ERRCODE		OUT		VARCHAR2
		,O_ERRMSG		OUT		VARCHAR2
  );
  
  PROCEDURE PROC_UP_DRIVER(
		IN_DR_ID		IN		VARCHAR2
		,IN_DR_NAME		IN		VARCHAR2
		,IN_DR_TEL		IN		VARCHAR2
		,IN_DR_GENDER	IN		VARCHAR2
		,O_ERRCODE		OUT		VARCHAR2
		,O_ERRMSG		OUT		VARCHAR2
  );
  
  PROCEDURE PROC_DEL_DRIVER(
		IN_DR_ID		IN		VARCHAR2
		,O_ERRCODE		OUT		VARCHAR2
		,O_ERRMSG		OUT		VARCHAR2
  );
  
  
  -- 멤버 CRUD
  PROCEDURE PROC_INS_MEMBER(
		IN_R_TEL		IN		VARCHAR2
		,O_ERRCODE		OUT		VARCHAR2
		,O_ERRMSG		OUT		VARCHAR2
  );
  
  PROCEDURE PROC_UP_MEMBER(
		IN_R_TEL		IN		VARCHAR2
		,IN_NEW_TEL		IN		VARCHAR2
		,O_ERRCODE		OUT		VARCHAR2
		,O_ERRMSG		OUT		VARCHAR2
  );
  
  PROCEDURE PROC_SEL_MEMBER(
		O_CURSOR		OUT		SYS_REFCURSOR
		,O_ERRCODE		OUT		VARCHAR2
		,O_ERRMSG		OUT		VARCHAR2
  );
  
  PROCEDURE PROC_DEL_MEMBER(
		IN_R_TEL		IN		VARCHAR2
		,O_ERRCODE		OUT		VARCHAR2
		,O_ERRMSG		OUT		VARCHAR2
  );
  

END PKG_DRIVER2;