-- 학과별로 학생수를 구하는 법 
SELECT T2.STU_DEPT_GRP, T2.STU_DEPT, T1.COM_VAL, COUNT(STU_ID) AS CNT  
FROM COMMONS_TBL T1, STUDENTS_TBL T2
WHERE T2.STU_DEPT_GRP(+) = T1.GRP_ID
AND T2.STU_DEPT(+) = T1.COM_ID
AND T1.GRP_ID = 'GRP002' AND T1.COM_LVL = 2
GROUP BY T2.STU_DEPT_GRP, T2.STU_DEPT, T1.COM_VAL
;
