-- MERGE INTO 
-- MS SQL 없음, PL SQL에만 존재 

SELECT * FROM DRIVERS_TBL;

-- DRIVERS_TBL에 입력된 값의 DR_ID가 존재하면 UPDATE, 없으면 INSERT 
MERGE INTO DRIVERS_TBL
USING DUAL
ON (DR_ID = 'DR001')
WHEN MATCHED THEN 
	UPDATE SET DR_NAME = '홍길동', DR_TEL = '010-6759-0954', DR_GENDER = 'M'
WHEN NOT MATCHED THEN
	INSERT VALUES('DR008', '최동수', '010-4266-3767', 'M')
;

-- 포인트 계산 프로시저 MERGE
MERGE INTO DR_MEMBER_TBL A
USING (
			SELECT R_TEL, SUM(NEW_POINT) AS MEM_POINT
			FROM
			(
			-- 건당 포인트 적립
			SELECT T3.R_TEL, T3.MEM_POINT, ROUND(R_PAY * 0.03) AS NEW_POINT
			FROM RESERVATION_TBL T1, FINISH_DRIVE_TBL T2, DR_MEMBER_TBL T3
			WHERE T1.R_ID = T2.R_ID
				AND T1.R_TEL = T3.R_TEL
				AND T2.F_GUBUN = 1
			)
			GROUP BY R_TEL
	)B
ON(A.R_TEL = B.R_TEL)
WHEN MATCHED THEN 
UPDATE SET A.MEM_POINT = B.MEM_POINT



