  CREATE TABLE JATOE_TBL
   (	
        STU_ID CHAR(6 BYTE), 
        STU_NAME VARCHAR2(30 BYTE) NOT NULL 
   );
   
   
   CREATE TABLE SCORES_HISTORY 
   (	
     STU_ID CHAR(6 BYTE), 
	 SUB_ID CHAR(7 BYTE), 
	 BEFORE_SCORE NUMBER(5,2), 
	 UPDATE_SCORE NUMBER(5,2)
   );
   
   
    CREATE TABLE STUDENTS_TRANSFER
   (	STU_ID CHAR(6 BYTE) NOT NULL, 
        TRANS_IDX NUMBER(*,0) NOT NULL, 
        BEFORE_DEPT CHAR(7 BYTE) NOT NULL,
	    BEFORE_GRP  CHAR(6 BYTE) NOT NULL, 
        TRANS_DEPT CHAR(7 BYTE) NOT NULL, 
        TRANS_GRP CHAR(6 BYTE) NOT NULL
   );
   
   
    CREATE TABLE STUDENTS_TRANSFER2 
   (	STU_ID CHAR(6 BYTE) NOT NULL, 
	   TRANS_IDX NUMBER(5) NOT NULL, 
	   STU_DEPT CHAR(7 BYTE) NOT NULL, 
	   STU_DEPT_GRP CHAR(6 BYTE) NOT NULL, 
	   GBN CHAR(1 BYTE) NOT NULL ENABLE
   );
   
   