create or replace NONEDITIONABLE TRIGGER TRG_INS_SAVE_FOR_BANKBOOK 
AFTER INSERT ON BANKBOOK 
REFERENCING OLD AS O NEW AS N 
FOR EACH ROW
DECLARE

    V_NEW_IDX       NUMBER(5);

BEGIN
  --INSERT INTO BANKBOOK VALUES('B004', '일반통장', 'M001');
  SELECT NVL(MAX(IDX),0) + 1
  INTO V_NEW_IDX
  FROM SAVE_TBL
  ;
  
  INSERT INTO SAVE_TBL(IDX, PRICE, GBN, BID)
  VALUES(V_NEW_IDX, 1000, 'I', :N.BID);
  
  
END;