-- 학생 별 수강신청 횟수 
SELECT 
	T1.STU_ID, T1.STU_NAME, COUNT(*) AS CNT
FROM 
	STUDENTS_TBL T1,
	STUDENTS_TIME_TBL T2
WHERE
	T1.STU_ID =  T2.STU_ID
GROUP BY 
	T1.STU_ID, 
	T1.STU_NAME
ORDER BY 
	T1.STU_ID
;

--1. 학과 별 학생리스트 
-- PARTITION BY 에 대해 공부해보기
-- 정렬전에 파트를 나누고 정렬을 할 것을 요구하는 함수	
-- GROUP BY 먹이기 전까지는 학생 별 수강 신청 리스트
SELECT 
	B.GRP_ID, 
	B.COM_ID, 
	B.PARTNAME, 
	A.STU_ID,
	A.STU_NAME, 
	COUNT(*),
	RANK() OVER(PARTITION BY B.GRP_ID,  B.COM_ID ORDER BY COUNT(*)DESC) AS RANK
FROM STUDENTS_TBL A,
(	
	SELECT 
		T2.GRP_ID, 
		T2.COM_ID, 
		T1.COM_ID AS COMID, 
		T1.COM_VAL || ' ' || T2.COM_VAL AS PARTNAME
	FROM 
		COMMONS_TBL T1, 
		COMMONS_TBL T2
	WHERE 
				T1.COM_ID = T2.PARENT_ID 
		AND T1.GRP_ID = T2.GRP_ID 
		AND T1.GRP_ID = 'GRP002' 
		AND T2.COM_LVL =2
)B, STUDENTS_TIME_TBL C
WHERE 
			A.STU_DEPT_GRP = B.GRP_ID 
	AND A.STU_DEPT = B.COM_ID
	AND A.STU_ID = C.STU_ID
GROUP BY  
	B.GRP_ID,
	B.COM_ID, 
	B.PARTNAME,
	A.STU_ID, 
	A.STU_NAME
ORDER BY
	B.COM_ID
;

-- 학생 별 총 수강 시수
SELECT 
	B.PARTNAME, A.STU_ID, STU_NAME, COUNT(*), SUM(D.SUB_CREDIT)
FROM STUDENTS_TBL A,
(	
	SELECT 
		T2.GRP_ID, 
		T2.COM_ID, 
		T1.COM_ID AS COMID, 
		T1.COM_VAL || ' ' || T2.COM_VAL AS PARTNAME
	FROM 
		COMMONS_TBL T1, 
		COMMONS_TBL T2
	WHERE 
				T1.COM_ID = T2.PARENT_ID 
		AND T1.GRP_ID = T2.GRP_ID 
		AND T1.GRP_ID = 'GRP002' 
		AND T2.COM_LVL =2
)B, STUDENTS_TIME_TBL C, SUBJECTS_TBL D
WHERE 
			A.STU_DEPT_GRP = B.GRP_ID 
	AND A.STU_DEPT = B.COM_ID
	AND A.STU_ID = C.STU_ID
	AND C.SUB_ID = D.SUB_ID
GROUP BY  
	B.PARTNAME, A.STU_ID, STU_NAME
;

SELECT 
	B.PARTNAME, A.STU_ID, STU_NAME, D.SUB_CREDIT
FROM STUDENTS_TBL A,
(	
	SELECT 
		T2.GRP_ID, 
		T2.COM_ID, 
		T1.COM_ID AS COMID, 
		T1.COM_VAL || ' ' || T2.COM_VAL AS PARTNAME
	FROM 
		COMMONS_TBL T1, 
		COMMONS_TBL T2
	WHERE 
				T1.COM_ID = T2.PARENT_ID 
		AND T1.GRP_ID = T2.GRP_ID 
		AND T1.GRP_ID = 'GRP002' 
		AND T2.COM_LVL =2
)B, STUDENTS_TIME_TBL C, SUBJECTS_TBL D
WHERE 
			A.STU_DEPT_GRP = B.GRP_ID 
	AND A.STU_DEPT = B.COM_ID
	AND A.STU_ID = C.STU_ID
	AND C.SUB_ID = D.SUB_ID

;